---
ID: "bacbb06a-7287-573c-99ae-05814359b13f"
Parent: "9948779e-259b-506c-b3e2-2813f2bbf5e8"
Template: "9948779e-259b-506c-b3e2-2813f2bbf5e8"
Path: "/sitecore/templates/Project/multisite_poc/Styleguide-FieldUsage-Custom/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220721T093912Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d78d2250-47b9-4def-83cb-d7b5da5eb59e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220721T093912Z
