---
ID: "910413e1-08c3-5b60-8d51-75c9d4bb8169"
Parent: "e94ca88c-f218-5aa1-b35e-7d06d3d1aec9"
Template: "e94ca88c-f218-5aa1-b35e-7d06d3d1aec9"
Path: "/sitecore/templates/Project/multisite_poc/Styleguide-Explanatory-Component/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220721T093907Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a1df525f-b63d-44a0-ac20-631de54ab7a6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220721T093907Z
