---
ID: "aae5e9bd-38cb-5e86-ade0-b78c11dfa4ca"
Parent: "78e4d3c0-e9b1-5996-840e-9766e1687448"
Template: "78e4d3c0-e9b1-5996-840e-9766e1687448"
Path: /sitecore/templates/Project/multisite_poc/ExampleCustomRouteType/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220721T093905Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fdbc7336-8f75-47c0-9d55-9af579969856"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220721T093905Z
